import { useMemo, useState } from 'react';
import { format, addDays, parseISO, startOfWeek, differenceInCalendarWeeks } from 'date-fns';
import { CheckCircle2, Circle, Trash2, RefreshCw, Plus, BookOpen, Clock, GraduationCap, X, ChevronDown, ChevronUp } from 'lucide-react';
import type { Assignment, Course, StudyBlock, TermConfig, StudyPreferences, ClassMeeting, MeetingType } from '../types';
import { generateStudyBlocks } from '../scheduler';

interface Props {
  courses: Course[];
  assignments: Assignment[];
  studyBlocks: StudyBlock[];
  today: Date;
  completedIds: Set<string>;
  onToggleCompleted: (id: string) => void;
  onToggle: (id: string) => void;
  onDelete: (id: string) => void;
  onSaveGenerated: (blocks: StudyBlock[]) => void;
  onAddBlock: (b: StudyBlock) => void;
  termConfig: TermConfig;
  studyPrefs?: StudyPreferences;
  classMeetings: ClassMeeting[];
  onAddMeeting: (m: ClassMeeting) => void;
  onDeleteMeeting: (id: string) => void;
  comprehensionScores?: Record<string, number>;
}

const MEETING_TYPES: MeetingType[] = ['lecture', 'lab', 'discussion', 'other'];
const DAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

function fmt12(time: string) {
  const t = time.trim();
  // Already has am/pm — just normalise spacing and capitalisation
  if (/am|pm/i.test(t)) {
    return t.replace(/\s*(am|pm)/i, (_, p) => ' ' + p.toUpperCase());
  }
  // 24-hr "HH:MM"
  const [h, m] = t.split(':').map(Number);
  if (isNaN(h) || isNaN(m)) return t; // return as-is if unparseable
  const ampm = h >= 12 ? 'PM' : 'AM';
  const h12 = h % 12 || 12;
  return `${h12}:${String(m).padStart(2, '0')} ${ampm}`;
}

export default function Schedule({
  courses, assignments, studyBlocks, today,
  completedIds, onToggleCompleted,
  onToggle, onDelete, onSaveGenerated, onAddBlock, termConfig, studyPrefs,
  classMeetings, onAddMeeting, onDeleteMeeting, comprehensionScores,
}: Props) {
  const [showAdd, setShowAdd] = useState<string | null>(null);
  const [showClassPanel, setShowClassPanel] = useState(true);
  const viewDays = 14;

  function classesForDay(date: string): ClassMeeting[] {
    const dow = parseISO(date).getDay();
    return classMeetings
      .filter(m => m.dayOfWeek === dow)
      .sort((a, b) => a.startTime.localeCompare(b.startTime));
  }

  const autoBlocks = useMemo(
    () => generateStudyBlocks(courses, assignments, studyBlocks, today, termConfig, studyPrefs, comprehensionScores),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [courses, assignments, today, termConfig, studyPrefs, comprehensionScores]
  );

  const allBlocks = useMemo(() => {
    const manual = studyBlocks.filter(b => !b.isAutoGenerated);
    return [...manual, ...autoBlocks];
  }, [studyBlocks, autoBlocks]);

  const days = useMemo(() =>
    Array.from({ length: viewDays }, (_, i) => format(addDays(today, i), 'yyyy-MM-dd')),
    [today]
  );

  // Stats
  const totalStudyThisWeek = useMemo(() => {
    const ws = format(startOfWeek(today, { weekStartsOn: 1 }), 'yyyy-MM-dd');
    const we = format(addDays(parseISO(ws), 6), 'yyyy-MM-dd');
    return allBlocks.filter(b => b.date >= ws && b.date <= we).reduce((s, b) => s + b.duration, 0);
  }, [allBlocks, today]);

  const completedThisWeek = useMemo(() => {
    const ws = format(startOfWeek(today, { weekStartsOn: 1 }), 'yyyy-MM-dd');
    const we = format(addDays(parseISO(ws), 6), 'yyyy-MM-dd');
    return allBlocks.filter(b => b.date >= ws && b.date <= we && b.isCompleted).length;
  }, [allBlocks, today]);

  const totalBlocksThisWeek = useMemo(() => {
    const ws = format(startOfWeek(today, { weekStartsOn: 1 }), 'yyyy-MM-dd');
    const we = format(addDays(parseISO(ws), 6), 'yyyy-MM-dd');
    return allBlocks.filter(b => b.date >= ws && b.date <= we).length;
  }, [allBlocks, today]);

  function blocksForDay(date: string) {
    return allBlocks
      .filter(b => b.date === date)
      .sort((a, b) => {
        if (a.isAutoGenerated !== b.isAutoGenerated) return a.isAutoGenerated ? 1 : -1;
        return 0;
      });
  }

  function eventsForDay(date: string) {
    return assignments.filter(a => a.dueDate === date && a.score === null && a.type !== 'participation');
  }

  // Group days into weeks for dividers
  const weeksMap = useMemo(() => {
    const map = new Map<number, string[]>();
    for (const date of days) {
      const weekNum = differenceInCalendarWeeks(parseISO(date), today, { weekStartsOn: 1 });
      if (!map.has(weekNum)) map.set(weekNum, []);
      map.get(weekNum)!.push(date);
    }
    return map;
  }, [days, today]);

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="text-lg font-bold text-gray-800 flex items-center gap-2">
            <span className="text-xl">🗓️</span> Smart Study Schedule
          </h2>
          <div className="flex items-center gap-2 mt-1.5 flex-wrap">
            <span className="flex items-center gap-1.5 px-3 py-1 bg-navy/10 rounded-full text-xs font-bold text-navy">
              ⏱️ {totalStudyThisWeek}min this week
            </span>
            {totalBlocksThisWeek > 0 && (
              <span className="flex items-center gap-1.5 px-3 py-1 bg-emerald-100 rounded-full text-xs font-bold text-emerald-700">
                ✅ {completedThisWeek}/{totalBlocksThisWeek} done
              </span>
            )}
          </div>
        </div>
        <button
          onClick={() => onSaveGenerated(autoBlocks)}
          className="flex items-center gap-1.5 px-3 py-1.5 bg-navy text-white text-sm rounded-lg hover:bg-navy/90 transition-colors"
        >
          <RefreshCw size={14} /> Regenerate
        </button>
      </div>

      {/* Class schedule panel */}
      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
        <button
          onClick={() => setShowClassPanel(p => !p)}
          className="w-full flex items-center justify-between px-5 py-3.5 hover:bg-gray-50 transition-colors"
        >
          <div className="flex items-center gap-2 text-sm font-bold text-navy">
            <span className="text-base">🎓</span>
            Class Schedule
            {classMeetings.length > 0 && (
              <span className="text-xs bg-navy text-white rounded-full px-2 py-0.5 font-bold">
                {classMeetings.length}
              </span>
            )}
          </div>
          <div className="flex items-center gap-2">
            {classMeetings.length > 0 && (
              <span
                role="button"
                onClick={e => {
                  e.stopPropagation();
                  if (confirm('Clear all class times?')) {
                    classMeetings.forEach(m => onDeleteMeeting(m.id));
                  }
                }}
                className="text-[11px] font-bold text-crimson/70 hover:text-crimson px-2 py-0.5 rounded-md hover:bg-crimson/5 transition-colors cursor-pointer"
              >
                Clear all
              </span>
            )}
            {showClassPanel ? <ChevronUp size={15} className="text-gray-400" /> : <ChevronDown size={15} className="text-gray-400" />}
          </div>
        </button>

        {showClassPanel && (
          <div className="border-t border-gray-100 px-5 py-4 space-y-4">
            {/* Existing meetings grouped by day */}
            {classMeetings.length === 0 ? (
              <p className="text-sm font-bold text-gray-300">N/A</p>
            ) : (
              <div className="space-y-1.5">
                {[1,2,3,4,5,0,6].map(dow => {
                  const dayMeetings = classMeetings.filter(m => m.dayOfWeek === dow);
                  if (dayMeetings.length === 0) return null;
                  return (
                    <div key={dow}>
                      <p className="text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-1">{DAY_NAMES[dow]}</p>
                      <div className="space-y-1">
                        {dayMeetings.sort((a,b) => a.startTime.localeCompare(b.startTime)).map(m => {
                          const course = courses.find(c => c.id === m.courseId);
                          return (
                            <div key={m.id} className="flex items-center gap-2.5 px-3 py-2 rounded-xl border group"
                              style={{ borderColor: (course?.color ?? '#aaa') + '40', background: (course?.color ?? '#aaa') + '0a' }}>
                              <div className="w-2 h-2 rounded-full flex-shrink-0" style={{ background: course?.color ?? '#aaa' }} />
                              <span className="text-xs font-bold" style={{ color: course?.color ?? '#aaa' }}>{course?.code}</span>
                              <span className="text-xs text-gray-600 truncate">{course?.name}</span>
                              <span className="text-xs text-gray-400 ml-auto">{fmt12(m.startTime)}–{fmt12(m.endTime)}</span>
                              {m.location && <span className="text-xs text-gray-400 hidden sm:inline">· {m.location}</span>}
                              <button onClick={() => onDeleteMeeting(m.id)}
                                className="p-1 text-gray-300 hover:text-crimson rounded transition-colors flex-shrink-0">
                                <X size={12} />
                              </button>
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  );
                })}
              </div>
            )}

            {/* Add new meeting form */}
            <AddMeetingForm courses={courses} onAdd={m => { onAddMeeting(m); }} />
          </div>
        )}
      </div>

      {/* Week groups */}
      {Array.from(weeksMap.entries()).map(([weekOffset, weekDays]) => (
        <div key={weekOffset}>
          {/* Week label */}
          <div className="flex items-center gap-3 mb-2">
            <span className={`text-xs font-bold px-3 py-1 rounded-full whitespace-nowrap ${
              weekOffset === 0
                ? 'bg-navy text-white'
                : weekOffset === 1
                  ? 'bg-amber-warm text-navy'
                  : 'bg-gray-100 text-gray-500'
            }`}>
              {weekOffset === 0 ? '⚡ This Week' : weekOffset === 1 ? '📅 Next Week' : `📆 Week of ${format(parseISO(weekDays[0]), 'MMM d')}`}
            </span>
            <div className="flex-1 h-px bg-gray-100" />
          </div>

          {/* Days in this week */}
          <div className="space-y-1.5">
            {weekDays.map(date => {
              const blocks = blocksForDay(date);
              const events = eventsForDay(date);
              const classes = classesForDay(date);
              const isToday = date === format(today, 'yyyy-MM-dd');
              const hasContent = blocks.length > 0 || events.length > 0 || classes.length > 0;
              const isAddOpen = showAdd === date;

              return (
                <div
                  key={date}
                  className={`rounded-xl border transition-colors overflow-hidden ${
                    isToday
                      ? 'border-navy/30 bg-navy/[0.04]'
                      : 'border-gray-100 bg-white'
                  }`}
                >
                  {/* Day header row */}
                  <div className={`flex items-start gap-3 px-4 ${hasContent || isAddOpen ? 'pt-3 pb-2' : 'py-2.5'}`}>
                    {/* Date column */}
                    <div className={`w-10 flex-shrink-0 text-center pt-0.5 ${isToday ? '' : ''}`}>
                      <p className={`text-[10px] font-bold uppercase tracking-wide ${isToday ? 'text-navy' : 'text-gray-400'}`}>
                        {format(parseISO(date), 'EEE')}
                      </p>
                      <p className={`text-xl font-bold leading-none mt-0.5 ${
                        isToday
                          ? 'text-white bg-navy rounded-lg w-8 h-8 flex items-center justify-center mx-auto'
                          : 'text-gray-700'
                      }`}>
                        {format(parseISO(date), 'd')}
                      </p>
                    </div>

                    {/* Content column */}
                    <div className="flex-1 min-w-0 space-y-2">
                      {/* Class meetings */}
                      {classes.map(m => {
                        const course = courses.find(c => c.id === m.courseId);
                        return (
                          <div key={m.id} className="flex items-center gap-2 rounded-lg px-3 py-1.5"
                            style={{ background: (course?.color ?? '#aaa') + '15', borderLeft: `3px solid ${course?.color ?? '#aaa'}` }}>
                            <GraduationCap size={12} style={{ color: course?.color ?? '#aaa' }} className="flex-shrink-0" />
                            <span className="text-xs font-bold flex-shrink-0" style={{ color: course?.color ?? '#aaa' }}>{course?.code}</span>
                            <span className="text-xs text-gray-600 truncate">{course?.name}</span>
                            <span className="text-xs text-gray-400 ml-auto flex-shrink-0">{fmt12(m.startTime)}–{fmt12(m.endTime)}{m.location ? ` · ${m.location}` : ''}</span>
                          </div>
                        );
                      })}

                      {/* Due items */}
                      {events.map(a => {
                        const course = courses.find(c => c.id === a.courseId);
                        const isExam = a.type === 'exam';
                        const done   = completedIds.has(a.id);
                        return (
                          <div
                            key={a.id}
                            className={`flex items-center gap-2.5 rounded-lg px-3 py-2 transition-opacity ${done ? 'opacity-50' : ''}`}
                            style={{
                              background: `${course?.color ?? '#aaa'}18`,
                              borderLeft: `3px solid ${done ? '#d1d5db' : (course?.color ?? '#aaa')}`,
                            }}
                          >
                            {/* Clickable checkbox */}
                            <button
                              onClick={() => onToggleCompleted(a.id)}
                              title={done ? 'Mark as not done' : 'Mark as done'}
                              className="flex-shrink-0 p-0.5 hover:scale-110 active:scale-95 transition-transform"
                            >
                              {done
                                ? <CheckCircle2 size={15} className="text-emerald-500" />
                                : <Circle
                                    size={15}
                                    className="transition-colors"
                                    style={{ color: course?.color ?? '#aaa' }}
                                  />
                              }
                            </button>
                            <div className="flex-1 min-w-0">
                              <span
                                className={`text-xs font-bold uppercase tracking-wide mr-1.5 ${done ? 'line-through text-gray-400' : ''}`}
                                style={done ? {} : { color: course?.color ?? '#aaa' }}
                              >
                                {isExam ? 'Exam' : a.type}
                              </span>
                              <span className={`text-sm font-medium ${done ? 'line-through text-gray-400' : 'text-gray-800'}`}>
                                {a.title}
                              </span>
                            </div>
                            <span className="text-xs text-gray-400 flex-shrink-0">
                              {done ? '✓ done' : course?.code}
                            </span>
                          </div>
                        );
                      })}

                      {/* Study blocks */}
                      {blocks.map(b => {
                        const course = courses.find(c => c.id === b.courseId);
                        const assignment = assignments.find(a => a.id === b.assignmentId);
                        return (
                          <div
                            key={b.id}
                            className={`flex items-center gap-3 rounded-lg px-3 py-2.5 transition-colors group ${
                              b.isCompleted
                                ? 'bg-gray-50 opacity-60'
                                : b.isAutoGenerated
                                ? 'bg-amber-warm/[0.07] hover:bg-amber-warm/10'
                                : 'bg-gray-50 hover:bg-gray-100'
                            }`}
                          >
                            {/* Check */}
                            <button
                              onClick={() => onToggle(b.id)}
                              className="flex-shrink-0"
                              title={b.isCompleted ? 'Mark incomplete' : 'Mark done'}
                            >
                              {b.isCompleted
                                ? <CheckCircle2 size={16} className="text-emerald-500" />
                                : <Circle size={16} className="text-gray-300 hover:text-gray-400 transition-colors" />
                              }
                            </button>

                            {/* Color bar */}
                            <div
                              className="w-1 self-stretch rounded-full flex-shrink-0"
                              style={{ background: course?.color ?? '#aaa' }}
                            />

                            {/* Text */}
                            <div className="flex-1 min-w-0">
                              <p className={`text-sm font-medium leading-tight truncate ${
                                b.isCompleted ? 'line-through text-gray-400' : 'text-gray-800'
                              }`}>
                                {assignment?.title ?? 'General Study'}
                              </p>
                              <p className="text-xs text-gray-400 mt-0.5">
                                {course?.code ?? 'Study'}
                                {b.isAutoGenerated && <span className="ml-1.5 text-brand-orange">· auto</span>}
                              </p>
                            </div>

                            {/* Duration */}
                            <span
                              className="text-xs font-bold px-2.5 py-0.5 rounded-full flex-shrink-0"
                              style={b.isCompleted
                                ? { background: '#f3f4f6', color: '#9ca3af' }
                                : { background: (course?.color ?? '#083152') + '22', color: course?.color ?? '#083152' }
                              }
                            >
                              {b.duration}m
                            </span>

                            {/* Delete */}
                            <button
                              onClick={() => onDelete(b.id)}
                              className="flex-shrink-0 p-1 text-gray-300 hover:text-crimson rounded transition-colors opacity-0 group-hover:opacity-100"
                              title="Remove block"
                            >
                              <Trash2 size={13} />
                            </button>
                          </div>
                        );
                      })}

                      {/* Empty state */}
                      {!hasContent && !isAddOpen && (
                        <p className="text-xs text-gray-300 py-0.5">No sessions scheduled</p>
                      )}
                    </div>

                    {/* Add button */}
                    <button
                      onClick={() => setShowAdd(isAddOpen ? null : date)}
                      className={`flex-shrink-0 mt-0.5 flex items-center gap-1 px-2 py-1 rounded-lg text-xs font-medium transition-colors ${
                        isAddOpen
                          ? 'bg-navy text-white'
                          : 'text-gray-400 hover:text-navy hover:bg-navy/5'
                      }`}
                    >
                      <Plus size={12} />
                      {!isAddOpen && <span className="hidden sm:inline">Add</span>}
                    </button>
                  </div>

                  {/* Add form */}
                  {isAddOpen && (
                    <AddBlockForm
                      date={date}
                      courses={courses}
                      assignments={assignments}
                      onAdd={b => { onAddBlock(b); setShowAdd(null); }}
                      onCancel={() => setShowAdd(null)}
                    />
                  )}
                </div>
              );
            })}
          </div>
        </div>
      ))}

      {/* Legend */}
      <div className="flex items-center gap-3 pt-1 pb-2 text-xs text-gray-400 flex-wrap">
        <div className="flex items-center gap-1.5 px-2.5 py-1 bg-amber-warm/10 rounded-full border border-amber-warm/20">
          <div className="w-2 h-2 rounded-full bg-amber-warm" />
          ✨ Auto block
        </div>
        <div className="flex items-center gap-1.5 px-2.5 py-1 bg-gray-50 rounded-full border border-gray-200">
          <div className="w-2 h-2 rounded-full bg-gray-300" />
          ✏️ Manual block
        </div>
        <div className="flex items-center gap-1.5 px-2.5 py-1 bg-crimson/5 rounded-full border border-crimson/15 text-crimson/70">
          ⚠️ Due date
        </div>
      </div>
    </div>
  );
}

// ─── Add Meeting Form ────────────────────────────────────────────────────────

function AddMeetingForm({ courses, onAdd }: { courses: Course[]; onAdd: (m: ClassMeeting) => void }) {
  const [open, setOpen]           = useState(false);
  const [courseId, setCourseId]   = useState(courses[0]?.id ?? '');
  const [days, setDays]           = useState<number[]>([1, 3]); // Mon + Wed default
  const [start, setStart]         = useState('');
  const [end, setEnd]             = useState('');
  const [location, setLocation]   = useState('');
  const [type, setType]           = useState<MeetingType>('lecture');

  function reset() {
    setCourseId(courses[0]?.id ?? '');
    setDays([1, 3]);
    setStart('');
    setEnd('');
    setLocation('');
    setType('lecture');
  }

  if (!open) {
    return (
      <button onClick={() => setOpen(true)}
        className="flex items-center gap-1.5 text-sm text-navy font-semibold hover:underline">
        <Plus size={14} /> Add class time
      </button>
    );
  }

  function toggleDay(d: number) {
    setDays(prev => prev.includes(d) ? prev.filter(x => x !== d) : [...prev, d].sort());
  }

  function submit() {
    if (!courseId || days.length === 0) return;
    // Create one ClassMeeting record per selected day
    for (const d of days) {
      onAdd({ id: crypto.randomUUID(), courseId, dayOfWeek: d, startTime: start, endTime: end, location, meetingType: type });
    }
    setOpen(false);
    reset();
  }

  const inp = 'border border-gray-200 rounded-lg px-2.5 py-1.5 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-navy/30';
  const sel = inp;

  return (
    <div className="bg-gray-50 rounded-xl p-4 border border-gray-100 space-y-3">
      <p className="text-xs font-semibold text-gray-600">New class time</p>

      {/* Row 1: Course + type */}
      <div className="flex flex-wrap gap-2">
        <select value={courseId} onChange={e => setCourseId(e.target.value)} className={sel}>
          {courses.map(c => <option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}
        </select>
        <select value={type} onChange={e => setType(e.target.value as MeetingType)} className={sel}>
          {MEETING_TYPES.map(t => <option key={t} value={t}>{t.charAt(0).toUpperCase() + t.slice(1)}</option>)}
        </select>
      </div>

      {/* Row 2: Day toggles */}
      <div>
        <p className="text-[11px] font-semibold text-gray-500 mb-1.5">Meets on</p>
        <div className="flex gap-1.5">
          {[
            { label: 'M', full: 'Monday',    val: 1 },
            { label: 'T', full: 'Tuesday',   val: 2 },
            { label: 'W', full: 'Wednesday', val: 3 },
            { label: 'R', full: 'Thursday',  val: 4 },
            { label: 'F', full: 'Friday',    val: 5 },
            { label: 'Sa', full: 'Saturday', val: 6 },
            { label: 'Su', full: 'Sunday',   val: 0 },
          ].map(d => (
            <button
              key={d.val}
              type="button"
              title={d.full}
              onClick={() => toggleDay(d.val)}
              className={`w-8 h-8 rounded-lg text-xs font-bold transition-all ${
                days.includes(d.val)
                  ? 'bg-navy text-white'
                  : 'bg-white border border-gray-200 text-gray-500 hover:border-navy/40'
              }`}
            >
              {d.label}
            </button>
          ))}
        </div>
        {days.length === 0 && <p className="text-[11px] text-crimson mt-1">Pick at least one day</p>}
      </div>

      {/* Row 3: Times + location */}
      <div className="flex flex-wrap items-center gap-2">
        <div>
          <p className="text-[11px] font-semibold text-gray-500 mb-1">Start time</p>
          <input
            value={start}
            onChange={e => setStart(e.target.value)}
            placeholder="N/A"
            className={`${inp} w-28`}
          />
        </div>
        <span className="text-gray-400 text-sm mt-4">to</span>
        <div>
          <p className="text-[11px] font-semibold text-gray-500 mb-1">End time</p>
          <input
            value={end}
            onChange={e => setEnd(e.target.value)}
            placeholder="N/A"
            className={`${inp} w-28`}
          />
        </div>
        <div>
          <p className="text-[11px] font-semibold text-gray-500 mb-1">Room (optional)</p>
          <input value={location} onChange={e => setLocation(e.target.value)} placeholder="e.g. Fincher 201" className={`${inp} w-36`} />
        </div>
      </div>

      <div className="flex gap-2 pt-1">
        <button onClick={submit} disabled={days.length === 0}
          className="px-4 py-1.5 bg-navy text-white text-sm font-medium rounded-lg hover:bg-navy/90 disabled:opacity-40">
          Add {days.length > 1 ? `(${days.length} days)` : ''}
        </button>
        <button onClick={() => { setOpen(false); reset(); }}
          className="px-3 py-1.5 bg-white border border-gray-200 text-gray-600 text-sm rounded-lg hover:bg-gray-50">
          Cancel
        </button>
      </div>
    </div>
  );
}

// ─── Add Block Form ─────────────────────────────────────────────────────────

function AddBlockForm({ date, courses, assignments, onAdd, onCancel }: {
  date: string;
  courses: Course[];
  assignments: Assignment[];
  onAdd: (b: StudyBlock) => void;
  onCancel: () => void;
}) {
  const [courseId, setCourseId] = useState(courses[0]?.id ?? '');
  const [assignmentId, setAssignmentId] = useState('');
  const [duration, setDuration] = useState(30);

  const courseAssignments = assignments.filter(a => a.courseId === courseId && a.score === null);

  function submit() {
    onAdd({
      id: crypto.randomUUID(),
      courseId,
      assignmentId: assignmentId || courseAssignments[0]?.id || '',
      date,
      duration,
      isCompleted: false,
      isAutoGenerated: false,
    });
  }

  return (
    <div className="border-t border-gray-100 bg-gray-50/60 px-4 py-3">
      <p className="text-xs font-semibold text-gray-500 mb-2.5 flex items-center gap-1.5">
        <BookOpen size={12} /> Add study block for {format(parseISO(date), 'EEEE, MMM d')}
      </p>
      <div className="flex flex-wrap gap-2 items-end">
        <div>
          <label className="text-xs text-gray-500 block mb-1">Course</label>
          <select
            value={courseId}
            onChange={e => { setCourseId(e.target.value); setAssignmentId(''); }}
            className="border border-gray-200 rounded-lg px-2.5 py-1.5 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-navy/30"
          >
            {courses.map(c => <option key={c.id} value={c.id}>{c.code}</option>)}
          </select>
        </div>
        <div>
          <label className="text-xs text-gray-500 block mb-1">For assignment</label>
          <select
            value={assignmentId}
            onChange={e => setAssignmentId(e.target.value)}
            className="border border-gray-200 rounded-lg px-2.5 py-1.5 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-navy/30 max-w-[200px]"
          >
            <option value="">General study</option>
            {courseAssignments.map(a => <option key={a.id} value={a.id}>{a.title}</option>)}
          </select>
        </div>
        <div>
          <label className="text-xs text-gray-500 block mb-1">Duration (min)</label>
          <input
            type="number" min={10} max={180} step={5} value={duration}
            onChange={e => setDuration(Number(e.target.value))}
            className="border border-gray-200 rounded-lg px-2.5 py-1.5 text-sm w-20 bg-white focus:outline-none focus:ring-2 focus:ring-navy/30"
          />
        </div>
        <button onClick={submit} className="px-4 py-1.5 bg-navy text-white text-sm font-medium rounded-lg hover:bg-navy/90 transition-colors">
          Add
        </button>
        <button onClick={onCancel} className="px-3 py-1.5 bg-white border border-gray-200 text-gray-600 text-sm rounded-lg hover:bg-gray-50 transition-colors">
          Cancel
        </button>
      </div>
    </div>
  );
}
