import type { Assignment, Course, StudyBlock } from './types';
import { apiUrl } from './apiUrl';

// Converts snake_case DB rows to camelCase frontend types
function toCourse(r: Record<string, unknown>): Course {
  return {
    id: r.id as string,
    name: r.name as string,
    code: r.code as string,
    creditHours: r.credit_hours as number,
    color: r.color as string,
    targetGrade: Number(r.target_grade),
    avgHomeworkHours: r.avg_homework_hours != null ? Number(r.avg_homework_hours) : null,
    overallGrade: r.overall_grade != null ? Number(r.overall_grade) : null,
  };
}

function toAssignment(r: Record<string, unknown>): Assignment {
  return {
    id: r.id as string,
    courseId: r.course_id as string,
    title: r.title as string,
    dueDate: (r.due_date as string).slice(0, 10),
    type: r.type as Assignment['type'],
    weight: Number(r.weight),
    score: r.score !== null && r.score !== undefined ? Number(r.score) : null,
    maxScore: Number(r.max_score),
    tentative: Boolean(r.tentative),
  };
}

function toBlock(r: Record<string, unknown>): StudyBlock {
  return {
    id: r.id as string,
    courseId: r.course_id as string,
    assignmentId: r.assignment_id as string,
    date: (r.date as string).slice(0, 10),
    duration: r.duration as number,
    isCompleted: r.is_completed as boolean,
    isAutoGenerated: r.is_auto_generated as boolean,
  };
}

async function apiFetch(path: string, token: string, options: RequestInit = {}) {
  const res = await fetch(apiUrl(`/api${path}`), {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
      ...options.headers,
    },
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`API ${options.method ?? 'GET'} ${path} failed (${res.status}): ${text}`);
  }
  if (res.status === 204) return null;
  return res.json();
}

// ── Courses ───────────────────────────────────────────────────────────────────

export async function getCourses(token: string): Promise<Course[]> {
  const rows = await apiFetch('/courses', token);
  return rows.map(toCourse);
}

export async function createCourse(token: string, data: Omit<Course, 'id'>): Promise<Course> {
  const row = await apiFetch('/courses', token, {
    method: 'POST',
    body: JSON.stringify({
      name: data.name, code: data.code, credit_hours: data.creditHours,
      color: data.color, target_grade: data.targetGrade,
      avg_homework_hours: data.avgHomeworkHours ?? null,
      overall_grade: data.overallGrade ?? null,
    }),
  });
  return toCourse(row);
}

export async function updateCourse(token: string, course: Course): Promise<Course> {
  const row = await apiFetch(`/courses/${course.id}`, token, {
    method: 'PUT',
    body: JSON.stringify({
      name: course.name, code: course.code, credit_hours: course.creditHours,
      color: course.color, target_grade: course.targetGrade,
      avg_homework_hours: course.avgHomeworkHours ?? null,
      overall_grade: course.overallGrade ?? null,
    }),
  });
  return toCourse(row);
}

export async function deleteCourse(token: string, id: string): Promise<void> {
  await apiFetch(`/courses/${id}`, token, { method: 'DELETE' });
}

// ── Assignments ───────────────────────────────────────────────────────────────

export async function getAssignments(token: string): Promise<Assignment[]> {
  const rows = await apiFetch('/assignments', token);
  return rows.map(toAssignment);
}

export async function createAssignment(token: string, data: Omit<Assignment, 'id'>): Promise<Assignment> {
  const row = await apiFetch('/assignments', token, {
    method: 'POST',
    body: JSON.stringify({
      course_id: data.courseId, title: data.title, due_date: data.dueDate,
      type: data.type, weight: data.weight, score: data.score, max_score: data.maxScore,
      tentative: data.tentative ?? false,
    }),
  });
  return toAssignment(row);
}

export async function updateAssignment(token: string, a: Assignment): Promise<Assignment> {
  const row = await apiFetch(`/assignments/${a.id}`, token, {
    method: 'PUT',
    body: JSON.stringify({
      title: a.title, due_date: a.dueDate, type: a.type,
      weight: a.weight, score: a.score, max_score: a.maxScore,
      tentative: a.tentative ?? false,
    }),
  });
  return toAssignment(row);
}

export async function deleteAssignment(token: string, id: string): Promise<void> {
  await apiFetch(`/assignments/${id}`, token, { method: 'DELETE' });
}

// ── Study Blocks ──────────────────────────────────────────────────────────────

export async function getStudyBlocks(token: string): Promise<StudyBlock[]> {
  const rows = await apiFetch('/study-blocks', token);
  return rows.map(toBlock);
}

export async function createStudyBlock(token: string, b: Omit<StudyBlock, 'id'>): Promise<StudyBlock> {
  const row = await apiFetch('/study-blocks', token, {
    method: 'POST',
    body: JSON.stringify({
      course_id: b.courseId, assignment_id: b.assignmentId || null, date: b.date,
      duration: b.duration, is_completed: b.isCompleted, is_auto_generated: b.isAutoGenerated,
    }),
  });
  return toBlock(row);
}

export async function bulkReplaceAutoBlocks(token: string, blocks: StudyBlock[]): Promise<StudyBlock[]> {
  const rows = await apiFetch('/study-blocks/bulk', token, {
    method: 'POST',
    body: JSON.stringify(blocks.map(b => ({
      course_id: b.courseId, assignment_id: b.assignmentId || null, date: b.date,
      duration: b.duration, is_completed: b.isCompleted, is_auto_generated: b.isAutoGenerated,
    }))),
  });
  return rows.map(toBlock);
}

export async function toggleStudyBlock(token: string, id: string): Promise<StudyBlock> {
  const row = await apiFetch(`/study-blocks/${id}/toggle`, token, { method: 'PATCH' });
  return toBlock(row);
}

export async function deleteStudyBlock(token: string, id: string): Promise<void> {
  await apiFetch(`/study-blocks/${id}`, token, { method: 'DELETE' });
}
