import { useState, useEffect, useCallback } from 'react';
import type { AppState, Assignment, Course, StudyBlock } from './types';
import * as api from './api';

const EMPTY: AppState = { courses: [], assignments: [], studyBlocks: [] };

export function useAppState(getToken: () => Promise<string | null>) {
  const [state, setState] = useState<AppState>(EMPTY);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    getToken().then(token => {
      if (!token) { setState(EMPTY); setLoading(false); return; }
      return Promise.all([
        api.getCourses(token),
        api.getAssignments(token),
        api.getStudyBlocks(token),
      ]).then(([courses, assignments, studyBlocks]) => {
        setState({ courses, assignments, studyBlocks });
        setError(null);
      });
    })
      .catch(e => setError(String(e)))
      .finally(() => setLoading(false));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const addCourse = useCallback(async (course: Course) => {
    const token = await getToken();
    if (!token) return;
    const { id: _id, ...data } = course;
    const created = await api.createCourse(token, data);
    setState(s => ({ ...s, courses: [...s.courses, created] }));
  }, [getToken]);

  const updateCourse = useCallback(async (course: Course) => {
    const token = await getToken();
    if (!token) return;
    const updated = await api.updateCourse(token, course);
    setState(s => ({ ...s, courses: s.courses.map(c => c.id === updated.id ? updated : c) }));
  }, [getToken]);

  const deleteCourse = useCallback(async (id: string) => {
    const token = await getToken();
    if (!token) return;
    await api.deleteCourse(token, id);
    setState(s => ({
      ...s,
      courses: s.courses.filter(c => c.id !== id),
      assignments: s.assignments.filter(a => a.courseId !== id),
      studyBlocks: s.studyBlocks.filter(b => b.courseId !== id),
    }));
  }, [getToken]);

  const addAssignment = useCallback(async (a: Assignment) => {
    const token = await getToken();
    if (!token) return;
    const { id: _id, ...data } = a;
    const created = await api.createAssignment(token, data);
    setState(s => ({ ...s, assignments: [...s.assignments, created] }));
  }, [getToken]);

  const updateAssignment = useCallback(async (a: Assignment) => {
    const token = await getToken();
    if (!token) return;
    const updated = await api.updateAssignment(token, a);
    setState(s => ({ ...s, assignments: s.assignments.map(x => x.id === updated.id ? updated : x) }));
  }, [getToken]);

  const deleteAssignment = useCallback(async (id: string) => {
    const token = await getToken();
    if (!token) return;
    await api.deleteAssignment(token, id);
    setState(s => ({
      ...s,
      assignments: s.assignments.filter(a => a.id !== id),
      studyBlocks: s.studyBlocks.filter(b => b.assignmentId !== id),
    }));
  }, [getToken]);

  const addStudyBlock = useCallback(async (b: StudyBlock) => {
    const token = await getToken();
    if (!token) return;
    const { id: _id, ...data } = b;
    const created = await api.createStudyBlock(token, data);
    setState(s => ({ ...s, studyBlocks: [...s.studyBlocks, created] }));
  }, [getToken]);

  const toggleStudyBlock = useCallback(async (id: string) => {
    const token = await getToken();
    if (!token) return;
    const updated = await api.toggleStudyBlock(token, id);
    setState(s => ({ ...s, studyBlocks: s.studyBlocks.map(b => b.id === updated.id ? updated : b) }));
  }, [getToken]);

  const deleteStudyBlock = useCallback(async (id: string) => {
    const token = await getToken();
    if (!token) return;
    await api.deleteStudyBlock(token, id);
    setState(s => ({ ...s, studyBlocks: s.studyBlocks.filter(b => b.id !== id) }));
  }, [getToken]);

  const saveGeneratedBlocks = useCallback(async (blocks: StudyBlock[]) => {
    const token = await getToken();
    if (!token) return;
    const saved = await api.bulkReplaceAutoBlocks(token, blocks);
    setState(s => ({
      ...s,
      studyBlocks: [...s.studyBlocks.filter(b => !b.isAutoGenerated), ...saved],
    }));
  }, [getToken]);

  return {
    state, loading, error,
    addCourse, updateCourse, deleteCourse,
    addAssignment, updateAssignment, deleteAssignment,
    addStudyBlock, toggleStudyBlock, deleteStudyBlock, saveGeneratedBlocks,
  };
}
