export interface Course {
  id: string;
  name: string;
  code: string;
  creditHours: number;
  color: string;
  targetGrade: number;
  avgHomeworkHours: number | null; // user's typical hours per homework assignment
  overallGrade: number | null;     // optional manual override — replaces computed grade everywhere
}

export type AssignmentType = 'exam' | 'quiz' | 'homework' | 'project' | 'participation' | 'other';

export interface Assignment {
  id: string;
  courseId: string;
  title: string;
  dueDate: string; // ISO date string YYYY-MM-DD
  type: AssignmentType;
  weight: number; // % of final course grade
  score: number | null; // null = not graded yet; 0-100
  maxScore: number;
  tentative: boolean; // true = date was not published in syllabus, spread as placeholder
}

export interface StudyBlock {
  id: string;
  courseId: string;
  assignmentId: string;
  date: string; // YYYY-MM-DD
  duration: number; // minutes
  isCompleted: boolean;
  isAutoGenerated: boolean;
}

export type TermType = 'semester' | 'trimester' | 'quarter';

export interface TermConfig {
  type: TermType;
  label: string;
  weeksPerTerm: number;
  termsPerYear: number;
  studyLookaheadDays: number;   // how far ahead to generate study blocks
  crunchLookaheadDays: number;  // how far ahead to scan for crunch weeks
}

export const TERM_CONFIGS: Record<TermType, TermConfig> = {
  semester: {
    type: 'semester',
    label: 'Semester',
    weeksPerTerm: 16,
    termsPerYear: 2,
    studyLookaheadDays: 21,
    crunchLookaheadDays: 42,
  },
  trimester: {
    type: 'trimester',
    label: 'Trimester',
    weeksPerTerm: 11,
    termsPerYear: 3,
    studyLookaheadDays: 14,
    crunchLookaheadDays: 28,
  },
  quarter: {
    type: 'quarter',
    label: 'Quarter',
    weeksPerTerm: 10,
    termsPerYear: 4,
    studyLookaheadDays: 10,
    crunchLookaheadDays: 21,
  },
};

export interface StudyPreferences {
  preferredDays: number[];       // 0=Sun … 6=Sat
  sessionDuration: number;       // minutes per block
  studyStyle: 'spread' | 'balanced' | 'crunch';
  productivityPeak: 'morning' | 'afternoon' | 'evening' | 'night';
  startTime: string;             // "HH:MM" 24-hr  (informational for now)
  endTime: string;               // "HH:MM" 24-hr
}

export const DEFAULT_STUDY_PREFS: StudyPreferences = {
  preferredDays: [1, 2, 3, 4, 5],   // Mon–Fri
  sessionDuration: 45,
  studyStyle: 'balanced',
  productivityPeak: 'afternoon',
  startTime: '09:00',
  endTime: '22:00',
};

export type OfficeHoursRole = 'professor' | 'ta' | 'other';

export interface OfficeHours {
  id: string;
  courseId: string;
  personName: string;
  role: OfficeHoursRole;
  dayOfWeek: number;   // 0=Sun 1=Mon … 6=Sat
  startTime: string;   // "HH:MM" 24-hr
  endTime: string;     // "HH:MM" 24-hr
  location: string;
}

export interface AppState {
  courses: Course[];
  assignments: Assignment[];
  studyBlocks: StudyBlock[];
}

export type MeetingType = 'lecture' | 'lab' | 'discussion' | 'other';

export interface ClassMeeting {
  id: string;
  courseId: string;
  dayOfWeek: number;   // 0=Sun … 6=Sat
  startTime: string;   // "HH:MM" 24-hr
  endTime: string;
  location: string;
  meetingType: MeetingType;
}

export interface SemesterRecord {
  id: string;
  label: string;       // e.g. "Fall 2024"
  gpa: number;
  creditHours: number;
}
